version: '{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet pack .\src\Orleans.Persistence.EntityFramework -c debug -o .\src\Orleans.Persistence.EntityFramework\publish
after_build:
artifacts:
 - path: '**\*.nupkg'
   name: Orleans.Persistence.EntityFramework
   type: NuGetPackage
clone_depth: 1
test_script:
  - cmd: dotnet restore --verbosity m
  - cmd: dotnet test .\test\Orleans.Persistence.EntityFramework.UnitTests
on_finish :
  
deploy: off
